#carga de librerias
library(dplyr)
library(lubridate)
library(tidyr)
library(naniar)
library(visdat)
library(stringr)
library(fpp2)
library(crop)
library(forecast)
library(ggplot2)
library(influxdbclient)
require (httr)
require (readr)
library(jsonlite)
library(tseries)
library(expsmooth)
library(ggthemes)
library(plotly)
library(htmlwidgets)
